name: Anchore Syft SBOM scan

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

jobs:
  Anchore-Build-Scan:
    permissions:
      actions: read
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.17.0
        with:
          push: false
          load: true
          tags: localbuild/testimage:latest
      - 
        name: Scan the image and upload dependency results
        uses: anchore/sbom-action@v0.20.0
        with:
          image: localbuild/testimage:latest
          artifact-name: github.sbom.json
          dependency-snapshot: false
          format: cyclonedx