name: Docker Image Grype scan

on:
  push:
    branches: [main]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.17.0
        with:
          push: false
          load: true
          tags: localbuild/testimage:latest
      -
        name: Scan image
        uses: anchore/scan-action@v6.2.0
        id: scan
        with:
          add-cpes-if-none: true
          fail-build: false
          image: localbuild/testimage:latest
      -
        name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3.28.18
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}